---@meta
-- AUTO-GENERATED by scripts/gen_curated_luals.py from the curated list in
-- config/luacheckrc.base.lua. Pre-dump LuaLS existence fallback for FrameXML
-- globals/constants Ketho doesn't cover. Superseded/augmented by /papidump defs.
---@type any
wipe = nil
---@type any
tinsert = nil
---@type any
tremove = nil
---@type any
tContains = nil
---@type any
unpack = nil
---@type any
strsplit = nil
---@type any
strjoin = nil
---@type any
strtrim = nil
---@type any
strmatch = nil
---@type any
strfind = nil
---@type any
strrep = nil
---@type any
strlower = nil
---@type any
strupper = nil
---@type any
strconcat = nil
---@type any
gsub = nil
---@type any
format = nil
---@type any
max = nil
---@type any
min = nil
---@type any
abs = nil
---@type any
floor = nil
---@type any
ceil = nil
---@type any
mod = nil
---@type any
date = nil
---@type any
time = nil
---@type any
geterrorhandler = nil
---@type any
securecall = nil
---@type any
issecure = nil
---@type any
issecurevariable = nil
---@type any
issecretvalue = nil
---@type any
GetTime = nil
---@type any
GetTimePreciseSec = nil
---@type any
debugprofilestop = nil
---@type any
BreakUpLargeNumbers = nil
---@type any
Enum = nil
---@type any
C_Texture = nil
---@type any
CreateFrame = nil
---@type any
UIParent = nil
---@type any
WorldFrame = nil
---@type any
GameTooltip = nil
---@type any
GameTooltip_Hide = nil
---@type any
UISpecialFrames = nil
---@type any
UIFrameFadeIn = nil
---@type any
UIFrameFadeOut = nil
---@type any
CreateColor = nil
---@type any
CreateColorFromHexString = nil
---@type any
Mixin = nil
---@type any
CreateFromMixins = nil
---@type any
hooksecurefunc = nil
---@type any
GetCursorPosition = nil
---@type any
GetPhysicalScreenSize = nil
---@type any
InCombatLockdown = nil
---@type any
C_Timer = nil
---@type any
PlaySound = nil
---@type any
PlaySoundFile = nil
---@type any
SOUNDKIT = nil
---@type any
PanelTemplates_SelectTab = nil
---@type any
PanelTemplates_DeselectTab = nil
---@type any
PanelTemplates_TabResize = nil
---@type any
PanelTemplates_SetNumTabs = nil
---@type any
PanelTemplates_SetTab = nil
---@type any
PanelTemplates_GetSelectedTab = nil
---@type any
ColorPickerFrame = nil
---@type any
PlayerSpellsFrame = nil
---@type any
ClassTalentFrame = nil
---@type any
InspectFrame = nil
---@type any
InterfaceOptionsFrame = nil
---@type any
C_Console = nil
---@type any
C_AutoComplete = nil
---@type any
GetAutoCompleteResults = nil
---@type any
AUTOCOMPLETE_FLAG_ALL = nil
---@type any
AutoCompleteEditBox_SetAutoCompleteSource = nil
---@type any
AutoCompleteEditBox_OnTextChanged = nil
---@type any
AutoCompleteEditBox_OnChar = nil
---@type any
AutoCompleteEditBox_OnKeyDown = nil
---@type any
AutoCompleteEditBox_OnKeyUp = nil
---@type any
AutoCompleteEditBox_OnEditFocusLost = nil
---@type any
AutoCompleteEditBox_OnTabPressed = nil
---@type any
AutoCompleteEditBox_OnEnterPressed = nil
---@type any
AutoCompleteEditBox_OnEscapePressed = nil
---@type any
GameFontNormal = nil
---@type any
GameFontNormalLarge = nil
---@type any
GameFontHighlight = nil
---@type any
GameFontHighlightSmall = nil
---@type any
GameFontDisable = nil
---@type any
GameFontDisableSmall = nil
---@type any
NumberFontNormal = nil
---@type any
InterfaceOptions_AddCategory = nil
---@type any
InterfaceOptionsFrame_OpenToCategory = nil
---@type any
Settings = nil
---@type any
SettingsPanel = nil
---@type any
UnitName = nil
---@type any
UnitExists = nil
---@type any
UnitClass = nil
---@type any
UnitLevel = nil
---@type any
UnitGUID = nil
---@type any
UnitIsUnit = nil
---@type any
UnitFullName = nil
---@type any
UnitInParty = nil
---@type any
UnitInRaid = nil
---@type any
UnitIsConnected = nil
---@type any
UnitIsPlayer = nil
---@type any
UnitHealth = nil
---@type any
UnitHealthMax = nil
---@type any
UnitPower = nil
---@type any
UnitPowerMax = nil
---@type any
UnitAffectingCombat = nil
---@type any
UnitStat = nil
---@type any
UnitGetTotalAbsorbs = nil
---@type any
IsInRaid = nil
---@type any
IsInGroup = nil
---@type any
IsInInstance = nil
---@type any
GetNumGroupMembers = nil
---@type any
GetNumSubgroupMembers = nil
---@type any
GetRealmName = nil
---@type any
GetNormalizedRealmName = nil
---@type any
UnitGroupRolesAssigned = nil
---@type any
GetSpecialization = nil
---@type any
GetSpecializationInfo = nil
---@type any
GetSpecializationInfoByID = nil
---@type any
GetLocale = nil
---@type any
GetCVar = nil
---@type any
SetCVar = nil
---@type any
GetCVarBool = nil
---@type any
GetCritChance = nil
---@type any
GetSpellCritChance = nil
---@type any
GetHaste = nil
---@type any
GetMastery = nil
---@type any
GetMasteryEffect = nil
---@type any
GetVersatilityBonus = nil
---@type any
GetCombatRating = nil
---@type any
GetCombatRatingBonus = nil
---@type any
GetDodgeChance = nil
---@type any
GetParryChance = nil
---@type any
GetBlockChance = nil
---@type any
GetAvoidance = nil
---@type any
GetSpeed = nil
---@type any
GetLifesteal = nil
---@type any
RAID_CLASS_COLORS = nil
---@type any
CLASS_ICON_TCOORDS = nil
---@type any
LOCALIZED_CLASS_NAMES_MALE = nil
---@type any
LOCALIZED_CLASS_NAMES_FEMALE = nil
---@type any
GetClassInfo = nil
---@type any
C_ClassColor = nil
---@type any
GetItemInfo = nil
---@type any
GetItemInfoInstant = nil
---@type any
GetItemIcon = nil
---@type any
GetItemCount = nil
---@type any
GetInventoryItemLink = nil
---@type any
GetInventoryItemDurability = nil
---@type any
GetInventoryItemTexture = nil
---@type any
GetInventorySlotInfo = nil
---@type any
C_Item = nil
---@type any
C_Container = nil
---@type any
C_TooltipInfo = nil
---@type any
C_CurrencyInfo = nil
---@type any
GetMoney = nil
---@type any
GetCoinTextureString = nil
---@type any
GetItemStats = nil
---@type any
GetAverageItemLevel = nil
---@type any
GetWeaponEnchantInfo = nil
---@type any
ITEM_QUALITY_COLORS = nil
---@type any
TooltipUtil = nil
---@type any
C_TradeSkillUI = nil
---@type any
GetDetailedItemLevelInfo = nil
---@type any
C_AttributeUtility = nil
---@type any
C_Attributes = nil
---@type any
C_Stats = nil
---@type any
BACKPACK_CONTAINER = nil
---@type any
NUM_BAG_SLOTS = nil
---@type any
NUM_TOTAL_EQUIPPED_BAG_SLOTS = nil
---@type any
INVSLOT_FIRST_EQUIPPED = nil
---@type any
INVSLOT_LAST_EQUIPPED = nil
---@type any
AuraUtil = nil
---@type any
C_UnitAuras = nil
---@type any
C_Spell = nil
---@type any
GetSpellInfo = nil
---@type any
C_SpellBook = nil
---@type any
C_ClassTalents = nil
---@type any
C_QuestLog = nil
---@type any
C_SuperTrack = nil
---@type any
GetQuestLink = nil
---@type any
GetSuperTrackedQuestID = nil
---@type any
C_TaskQuest = nil
---@type any
C_QuestInfoSystem = nil
---@type any
GetAchievementInfo = nil
---@type any
GetCategoryInfo = nil
---@type any
GetStatistic = nil
---@type any
GetComparisonStatistic = nil
---@type any
C_AchievementInfo = nil
---@type any
GetAchievementNumCriteria = nil
---@type any
GetAchievementCriteriaInfo = nil
---@type any
GetCategoryList = nil
---@type any
GetCategoryNumAchievements = nil
---@type any
C_DateAndTime = nil
---@type any
C_Map = nil
---@type any
GetRealZoneText = nil
---@type any
GetSubZoneText = nil
---@type any
GetMinimapZoneText = nil
---@type any
IsResting = nil
---@type any
GetZoneText = nil
---@type any
C_MythicPlus = nil
---@type any
C_ChallengeMode = nil
---@type any
C_WeeklyRewards = nil
---@type any
C_PlayerInfo = nil
---@type any
C_ChatInfo = nil
---@type any
C_AddOns = nil
---@type any
C_CVar = nil
---@type any
GetAddOnMetadata = nil
---@type any
RegisterAddonMessagePrefix = nil
---@type any
SendAddonMessage = nil
---@type any
Ambiguate = nil
---@type any
GetBuildInfo = nil
---@type any
GetServerTime = nil
---@type any
BackdropTemplateMixin = nil
---@type any
CombatLogGetCurrentEventInfo = nil
---@type any
StaticPopup_Show = nil
---@type any
StaticPopupDialogs = nil
---@type any
SlashCmdList = nil
---@type any
ACCEPT = nil
---@type any
DECLINE = nil
---@type any
OKAY = nil
---@type any
CANCEL = nil
---@type any
CLOSE = nil
---@type any
YES = nil
---@type any
NO = nil
