#!/usr/bin/env python3
"""Turn an in-game /papidump into a version-accurate luacheck std.

Reads the PeaversAPIDump SavedVariables file and writes
    build/<BUILD>/wow-globals.lua   (a Lua module returning { read_globals = {...} })
which config/luacheckrc.base.lua loads automatically when present (else it falls back to
its curated list, so deleting the generated file is always safe).

Usage:
    python3 scripts/gen_wow_api.py                 # auto-locate the newest dump
    python3 scripts/gen_wow_api.py --sv PATH       # explicit SavedVariables file
    python3 scripts/gen_wow_api.py --wow-root DIR  # search a specific WoW install

Workflow:
    1. In-game: enable "Peavers API Dump", /papidump, then /reload.
    2. python3 scripts/gen_wow_api.py
    3. luacheck now checks against the real client API.
"""
import argparse
import glob
import os
import re
import sys

# Standard Lua libs/globals: leave these to luacheck's built-in lua51 std (keeps its
# stricter field checking for string/table/math/etc.). WoW extras (strsplit, wipe...)
# are NOT here, so they still get captured from _G.
# NOTE: not 'bit' — luacheck's lua51 std has no bit library, so we keep WoW's from _G.
DENY = {
    "_G", "_VERSION", "assert", "collectgarbage", "dofile", "error", "getfenv",
    "getmetatable", "ipairs", "load", "loadfile", "loadstring", "module", "next",
    "pairs", "pcall", "print", "rawequal", "rawget", "rawlen", "rawset", "require",
    "select", "setfenv", "setmetatable", "tonumber", "tostring", "type", "unpack",
    "xpcall", "string", "table", "math", "os", "io", "coroutine", "debug",
}

# The dump addon's own globals — never emit these into the shared std.
SELF_PREFIXES = ("PeaversAPIDump", "SLASH_PAPIDUMP")

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Common SavedVariables locations across platforms. %s = WoW root.
WOW_ROOTS = [
    "/Applications/World of Warcraft/_retail_",
    os.path.expanduser("~/Applications/World of Warcraft/_retail_"),
    r"C:\Program Files (x86)\World of Warcraft\_retail_",
]


def find_sv(explicit, wow_root):
    if explicit:
        return explicit
    roots = [wow_root] if wow_root else WOW_ROOTS
    candidates = []
    for root in roots:
        if not root:
            continue
        pattern = os.path.join(root, "WTF", "Account", "*", "SavedVariables",
                               "PeaversAPIDump.lua")
        candidates.extend(glob.glob(pattern))
    if not candidates:
        return None
    return max(candidates, key=os.path.getmtime)


def extract(text, key):
    m = re.search(r'\["%s"\]\s*=\s*"([^"]*)"' % re.escape(key), text)
    return m.group(1) if m else None


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--sv", help="explicit path to PeaversAPIDump.lua")
    ap.add_argument("--wow-root", help="WoW _retail_ directory to search")
    args = ap.parse_args()

    sv = find_sv(args.sv, args.wow_root)
    if not sv or not os.path.exists(sv):
        sys.exit("No PeaversAPIDump.lua found. Run /papidump then /reload in-game first.\n"
                 "Searched: " + ", ".join(WOW_ROOTS))
    print("Reading %s" % sv, file=sys.stderr)

    with open(sv, encoding="utf-8", errors="replace") as fh:
        text = fh.read()

    raw = extract(text, "globals")
    if raw is None:
        sys.exit("Could not find the 'globals' field in the dump.")
    build = extract(text, "build") or "unknown"
    # The interface build tag (e.g. "120007") for the output directory.
    bm = re.search(r"interface\s+(\d+)", build)
    build_tag = bm.group(1) if bm else "unknown"

    # Captured value has literal \n separators (WoW escapes newlines in SV strings).
    ids = [i for i in raw.split("\\n") if i]

    plain = set()
    namespaces = {}  # head -> set of fields
    for ident in ids:
        if ident.startswith(SELF_PREFIXES):
            continue
        if "." not in ident:
            if ident not in DENY:
                plain.add(ident)
        else:
            head, field = ident.split(".", 1)
            if head in DENY:
                continue
            namespaces.setdefault(head, set()).add(field)

    # A name that has descended fields is emitted as a namespace table, not a plain global.
    plain -= set(namespaces)

    lines = [
        "-- AUTO-GENERATED by scripts/gen_wow_api.py from an in-game /papidump. Do not edit.",
        "-- Client build: %s" % build,
        "return {",
        "  read_globals = {",
    ]
    for name in sorted(plain):
        lines.append('    "%s",' % name)
    for name in sorted(namespaces):
        fields = ", ".join('"%s"' % f for f in sorted(namespaces[name]))
        lines.append("    %s = { fields = { %s } }," % (name, fields))
    lines += ["  },", "}", ""]

    out_dir = os.path.join(REPO_ROOT, "build", build_tag)
    os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, "wow-globals.lua")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print("Wrote %s: %d globals + %d namespaces (build %s)"
          % (out, len(plain), len(namespaces), build), file=sys.stderr)


if __name__ == "__main__":
    main()
