#!/usr/bin/env python3
"""Derive a LuaLS existence-stub fallback from the curated luacheck list.

Ketho's vendored annotations cover the C_* / system API but its FrameXML layer is sparse,
so FrameXML globals and UI constants (CLASS_ICON_TCOORDS, SOUNDKIT, PanelTemplates_*, ...)
read as undefined under LuaLS until a real /papidump is generated. This emits
    config/curated-globals.lua
declaring every curated read_globals name as `any`, so LuaLS knows they exist pre-dump.
It mirrors the SAME curated list in config/luacheckrc.base.lua (one source of truth) — when
build/<BUILD>/luals/wow-globals.lua (from /papidump) is present it simply augments this.

Run after editing the curated list:
    python3 scripts/gen_curated_luals.py
"""
import os
import re

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = os.path.join(REPO_ROOT, "config", "luacheckrc.base.lua")
OUT = os.path.join(REPO_ROOT, "config", "curated-globals.lua")

# Names that are Lua std tables extended via `fields` in the curated list, or otherwise
# not WoW globals to stub. Keep LuaLS's own std for these.
SKIP = {"string", "table", "math", "bit", "_G", "fields", "read_globals"}


def main():
    with open(BASE, encoding="utf-8") as fh:
        text = fh.read()

    # Isolate the curated table so we don't pick up identifiers from comments/other code.
    m = re.search(r"local curated = \{(.*?)\n\}", text, re.DOTALL)
    body = m.group(1) if m else text

    # Drop `fields = { ... }` sub-blocks — their strings are library-extension fields
    # (split, join, band, ...), not globals to stub.
    body = re.sub(r"fields\s*=\s*\{[^}]*\}", "", body)

    # Every double-quoted identifier in the curated block is a global name.
    names = []
    seen = set()
    for tok in re.findall(r'"([A-Za-z_][A-Za-z0-9_]*)"', body):
        if tok in SKIP or tok in seen:
            continue
        # field strings like "split"/"join"/"band" live inside `fields = { ... }`; skip the
        # lowercase library-extension fields (heuristic: they're not WoW-cased globals).
        seen.add(tok)
        names.append(tok)

    lines = [
        "---@meta",
        "-- AUTO-GENERATED by scripts/gen_curated_luals.py from the curated list in",
        "-- config/luacheckrc.base.lua. Pre-dump LuaLS existence fallback for FrameXML",
        "-- globals/constants Ketho doesn't cover. Superseded/augmented by /papidump defs.",
    ]
    for n in names:
        lines.append("---@type any")
        lines.append("%s = nil" % n)

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("Wrote %s (%d stubs)" % (OUT, len(names)))


if __name__ == "__main__":
    main()
